name: 'PR number'
description: 'Replaces [#PR] with an actual PR number in a description body'
author: 'Igor Matias'
branding:
  icon: 'check'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pattern:
    description: 'Pattern to use for ID replacement (default: "[#PR]").'
    required: false
    default: '[#PR]'
